### ISSUE TITLE
Next.js support

### ISSUE THREAD

**Issue by yunying1** [onlyhom/mobile-select#100]
I migrating my project to `Next.js`, but i got a waring at `mobile-select`.

<img width="751" alt="image" src="https://user-images.githubusercontent.com/50652358/188351152-1c2ee9e4-5dc6-43e9-b8ca-fd679c55fee2.png">

Reason is `Next.js` restrict global css import, `Next.js` requirement publish a complied version, do you can support `Next.js`?

Related links: [https://nextjs.org/docs/messages/css-npm#possible-ways-to-fix-it](https://nextjs.org/docs/messages/css-npm#possible-ways-to-fix-it)

**Comment by yunying1** [comment]
Maybe i can submit a PR but i want to know how to not use global css just load css at component. I exclude `css in js` because it's too troublesome.

**Comment by onlyhom** [comment]
hi, maybe you can try [next-transpile-modules](https://github.com/martpie/next-transpile-modules)?
This plugin aims to solve transpilation from node_modules packages.

## Examples

```shell
npm i next-transpile-modules -D
```

```js
// next.config.js

const withTM = require('next-transpile-modules')(['mobile-select']); // pass the modules you would like to see transpiled
const nextConfig = {...}
module.exports = withTM(nextConfig);
```

Then this error will go away. 

-------
## Refer Article
1.https://github.com/vercel/next.js/discussions/32219
2.https://github.com/fullcalendar/fullcalendar-example-projects/tree/88fd2bfa91b310b4814b699932970dfb1aef4586/next

**Comment by yunying1** [comment]
Hey, it's working.
I've tried two options:
[next-global-css](https://github.com/bem/next-global-css)
[next-transpile-modules](https://github.com/martpie/next-transpile-modules)

Thank you!
