### ISSUE TITLE
Bug: the select cannot show under ios 15.4.1 safari

### ISSUE THREAD

**Issue by vanpipy** [onlyhom/mobile-select#103]
## version
ios 15.4.1 safari

## reproduce
1. create any select under safari
2. trigger it

## current behavior
The select cannot show cause the relative position did not work as wish, try to move to 

```
position: absolute;
top: 0;
right: 0;
bottom: 0;
left: 0;
```

for the `.ms-mobile-select` can fix it, but please take a look this to evaluate the effect scope.

## expected behavior
The select can show as wish

**Comment by vanpipy** [comment]
Try to rewrite the `.ms-mobile-select` has the style as follow:

```
position: absolute;
top: 0;
right: 0;
bottom: 0;
left: 0;
transform: translate(0, 0);
```

and it works as wish.

**Comment by onlyhom** [comment]
Thank you for your detailed issue and PR, which is of great help to me without IOS devices. :D
Now you can reinstall mobile-select with version 1.3.4
