### ISSUE TITLE
关于样式冲突的问题

### ISSUE THREAD

**Issue by CrystalGrape** [onlyhom/mobile-select#50]
您好。我在使用中发现了一个样式表的冲突问题。    
如果我在我的代码中直接对ul标签和li标签定义样式的话，似乎会导致mobileSelect弹出的列表框出现问题，下面有我使用时出现的问题重现。
比如，我的样式：
<pre>ul {
    overflow: hidden;    
    white-space: nowrap;     
    width:100%;
    padding:0 0 20px 0;
}
.li {
    list-style: none;
    float: left;
    width: 33.33%;
    text-align: center;
    font-size: 13px;
    border: 1px solid rgb(240,240,240);
    padding: 10px;
}
</pre>
弹出的列表：
![default](https://user-images.githubusercontent.com/9365300/37887153-cbd2a4e6-30f2-11e8-8fdb-0faf3d4b8582.PNG)
我发现_public.css文件几乎全部是直接对标签定义样式，这是否会导致更多的样式冲突问题呢？    
谢谢！

**Comment by onlyhom** [comment]
您好
问题一：在项目中直接对ul li操作，建议添加class前缀，不要对全局ul li进行操作
问题二： public.css是在demo.html中使用的，在项目中使用并不需要用到，现文件已更名为demo.css 防止误会
