### ISSUE TITLE
多级联动怎么找到指定轮子的位置实现重新定位轮子的位置呢？

### ISSUE THREAD

**Issue by ljy9418** [onlyhom/mobile-select#52]

**Comment by onlyhom** [comment]
在v1.2.0+版本中增加了```initValue```属性，只需要回传具体的value值，组件会自动定位位置

**Comment by 349989153** [comment]
> 在v1.2.0+版本中增加了`initValue`属性，只需要回传具体的value值，组件会自动定位位置

如果多级联动才能用initValue，那应该在文档里重点标出来吧，initValue will fail if each wheel is unconnected.

如果是几个单独的wheel，initValue会导致报错，用position才可以

https://github.com/onlyhom/mobile-select/issues/112
