### ISSUE TITLE
点击选择时,又时会出现renderWheels 时 会渲染多次

### ISSUE THREAD

**Issue by xcqweb** [onlyhom/mobile-select#55]
点击选择时,又时会出现renderWheels 时 会渲染多次 ,打开控制台 发现确实是
重复渲染的代码:
`<div class="grayLayer"></div>'+
		        '<div class="content">'+
		            '<div class="btnBar">'+
		                '<div class="fixWidth">'+
		                    '<div class="cancel">取消</div>'+
		                    '<div class="title"></div>'+
		                    '<div class="ensure">选择</div>'+
		                '</div>'+
		            '</div>'+
		            '<div class="panel">'+
		                '<div class="fixWidth">'+
		                	'<div class="wheels">'+
			                '</div>'+
		                    '<div class="selectLine"></div>'+
		                    '<div class="shadowMask"></div>'+
		                '</div>'+
		            '</div>'+
		        '</div>';`

vue项目中使用了fastclick

 ,不知道会不会有影响

初步判断是事件默认行为搞得怪 ,在注册事件时阻止默认行为后,问题视乎被解决了,暂时没出现bug
修改代码如下:
_this.trigger && _this.trigger.addEventListener('touchstart',function(e){
				e.preventDefault();
		    	_this.mobileSelect.classList.add('mobileSelect-show');
		    });
		    _this.grayLayer.addEventListener('touchstart',function(e){
				e.preventDefault();
		    	_this.mobileSelect.classList.remove('mobileSelect-show');
		    });
		    _this.popUp.addEventListener('touchstart',function(e){
				e.preventDefault();
		    	event.stopPropagation(); 
		    });

**Comment by onlyhom** [comment]
此问题已修复，在v1.2.0+版本中增加了```destroy()```方法
在vue中使用时，在vue组件销毁时调用```destroy()```方法即可，具体例子可参考在线demo:  https://codesandbox.io/s/mobile-select-vue-el5o6r
