### ISSUE TITLE
多次进入，重复生成picker

### ISSUE THREAD

**Issue by qidaping** [onlyhom/mobile-select#56]
is:issue is:open在H5项目中使用时候，在某一个页面需要这个picker，然后我在这个页面点击返回 然后再进来  每进来一次都在dom上生成一个新的picker

**Comment by ShunLinjiang** [comment]
同遇到这个问题；我的解决办法是 把其他的隐藏掉

**Comment by onlyhom** [comment]
此问题已修复，在v1.2.0+版本中增加了```destroy()```方法，在页面&组件销毁时调用```destroy()```方法即可
