### ISSUE TITLE
public.css中定义了很多全局的样式，是否对网站既有样式产生了侵袭

### ISSUE THREAD

**Issue by aricc** [onlyhom/mobile-select#58]
想使用这个插件，但发现用了它，就会对我已有的样式产生影响。
如果能做到不依赖、不影响，就个好插件。
另外，是否可以把CSS合为一个文件？

**Comment by onlyhom** [comment]
public.css 里面的样式是提供给demo.html使用的，只有mobile-select.css才是属于插件范围内的样式
