### ISSUE TITLE
希望加个销毁的函数

### ISSUE THREAD

**Issue by kanbekotori** [onlyhom/mobile-select#70]
如题，看源码里没有提供销毁组件的函数，事件都是匿名函数，就算用cloneNode的方式移除了select的事件，trigger上的事件不知道如何移除。

**Comment by xiaopanshi** [comment]
我也发现了，没有销毁函数好像是缺了点什么

**Comment by onlyhom** [comment]
此问题已修复，在v1.2.0+版本中增加了```destroy()```方法
