### ISSUE TITLE
为什么点击mobileSelect中的li会有背景颜色？

### ISSUE THREAD

**Issue by jeremyChenMing** [onlyhom/mobile-select#80]
点击确认、取消也是一样的，会有背景颜色，找不出来是哪里的，还有就是容器组件，点击的时候也又蓝色，这个是在移动端发现的，pc上没有背景颜色，这事为什么？

**Comment by Anthony0416** [comment]
我也碰到了这个问题，发现只有安卓才会出现，其他设备不会有，附上解决方案：
在css里搜 .mobileSelect .content .panel .wheel .selectContainer li 
在里面加上 -webkit-tap-highlight-color: transparent;

**Comment by onlyhom** [comment]
此问题已修复，在v1.2.0+ 版本中的css中已自带  ```-webkit-tap-highlight-color: transparent; ``` 修复此问题
