### ISSUE TITLE
在vue中，切换页面后，无法在body中销毁，导致下次再次进入时，又重复在body中挂载了很多实例。

### ISSUE THREAD

**Issue by MrTan123** [onlyhom/mobile-select#92]
![image](https://user-images.githubusercontent.com/40554087/154439174-74e6e032-2cad-4929-9684-36a9e0467f91.png
一直疯狂创建
<div class="mobileSelect">XXX</div>
<div class="mobileSelect">XXX</div>
<div class="mobileSelect">XXX</div>
这样子也无法根据dom元素删除掉

**Comment by onlyhom** [comment]
此问题已修复，在v1.2.0版本中增加了```destroy()```方法
在vue中使用时，在vue组件销毁时调用```destroy()```方法即可，具体例子可参考在线demo:  [mobile-select use in vue](https://codesandbox.io/s/mobile-select-vue-el5o6r)
