### ISSUE TITLE
滚轮中间的两条横线无法显示

### ISSUE THREAD

**Issue by michael20102013** [onlyhom/mobile-select#94]
主页中的sandebox就可以复现
https://codesandbox.io/s/mobile-select-vue-el5o6r?file=/src/components/MobileSelect.vue
![image](https://user-images.githubusercontent.com/25799165/185099199-cb376d9e-bdd7-4463-9d12-e8f859439684.png)

**Comment by onlyhom** [comment]
谢谢指正，此问题已修复，请在最新版本v1.2.0-beta.3体验，主页sandbox也已更新
