### ISSUE TITLE
[BUG] Wrong `data-index` when drag a blank position.

### ISSUE THREAD

**Issue by yunying1** [onlyhom/mobile-select#95]
Hi, thank you for your great library.

When we drag a blank position, We'll get a wrong `data-index`, It's `0`. So `select-container` with index `0` get a wrong `transform`.
<img width="316" alt="image" src="https://user-images.githubusercontent.com/50652358/185589632-dc66bd9b-8c64-46a4-a294-ef54f1205888.png">

**Comment by onlyhom** [comment]
Thanks to your PR. Now you can download the latest v1.2.0-beta.4 to use it.
